# This sript loads the data generated by BestBandwidthFinder and identifies the best
# linear model. The results are shown through a series of scatter plot.

# Import required libraries
library(KDEModelIdentification) # Needed for model
library(KDEPlotTools) # Needed for the plot
library(stats) # Needed for predict


# load the data from file
files = c("Data/multiGaussianBand.rds", "Data/gaussianBand.rds", "Data/parabolicBand.rds")

for(file in files){
  
  # load data from file
  dataFrame = readRDS(file = file)
  faultNumbers = dataFrame$faultNumbers
  fittedBandwidth = dataFrame$fittedBandwidth
  
  # Plot the results
  scatterPlot(x = faultNumbers, y = fittedBandwidth, title =  "Optimal bandwidth vs faults",
              sub = bquote("Number of simulations:"~.(length(faultNumbers))), 
              xlab = "Faults", ylab = "Bandwidth"
  )
  
  # Identify polynomial model
  grades = 1:8
  newData = seq(from = min(faultNumbers), to = max(faultNumbers), length.out = 250)
  predictions = fitLinearModels(x = faultNumbers, y = fittedBandwidth, grades = grades, newData = newData)
  
  # And plotting them
  for(i in 1 : length(grades)){
    par(new = TRUE) # plot in the same graphic window
    modelPlot(x = newData, y = predictions[[i]],
              xlim = c(min(faultNumbers), max(faultNumbers)), 
              ylim = c(min(fittedBandwidth), max(fittedBandwidth)),
              col = rainbow(length(grades))[i]
    )
  }
  
  # Find the best model using AIC 
  bestFit = findBestModel(x = faultNumbers, y = fittedBandwidth, interval = c(min(grades), max(grades)))
  bestBandwidth = findMinimumFromModel(model = bestFit, interval = c(min(faultNumbers), max(faultNumbers)))$minimum
  par(new = FALSE) # create a new plot
  scatterPlot(x = faultNumbers, y = fittedBandwidth, title = "Optimal bandwidth vs faults", 
              sub = bquote("Simulations:"~.(length(faultNumbers))~"  Best rank:"~.(bestFit$rank - 1)),
              xlab = "Faults", ylab = "Bandwidth")
  par(new = TRUE) # plot in the same graphic window
  prediction = predict(bestFit, newdata =  data.frame(x = newData))
  modelPlot(x = newData, y = prediction, col = "red",
            xlim = c(min(faultNumbers), max(faultNumbers)), ylim = c(min(fittedBandwidth), max(fittedBandwidth))
  )
}

