# This sript loads the data generated by BestBandwidthFinder and identifies the best
# linear model. The mean of the three curves represent the best bandwidth for an
# unknown distribution.

# Initilize parameters
minFaults = 10
maxFaults = 60
faults = seq(from = minFaults, to = maxFaults, by = 1)
bandCurve = numeric(length = length(faults))

# Import required libraries
library(KDEModel) # Needed for model
library(KDEPlotTools) # Needed for the plot
library(stats) # Needed for predict


# load the data from file
files = c("Data//TemporaryData/maxLikelihoodBestBandwidths.rds")

for(file in files){
  
  # load data from file
  dataFrame = readRDS(file = file)
  faultNumbers = dataFrame$faults
  fittedBandwidth = dataFrame$bestBand
  
  # Identify polynomial model
  grades = 1:8
  newData = seq(from = min(faultNumbers), to = max(faultNumbers), length.out = 250)
  predictions = fitLinearModels(x = faultNumbers, y = fittedBandwidth, grades = grades, newData = newData)
  
  # Find the best model using AIC 
  bestFit = findBestModel(x = faultNumbers, y = fittedBandwidth, interval = c(min(grades), max(grades)))
  bestBandwidth = findMinimumFromModel(model = bestFit, interval = c(min(faultNumbers), max(faultNumbers)))$minimum
  bandCurve = bandCurve + predict(bestFit, newdata =  data.frame(x = faults))/length(files)
}

par(new = FALSE)
plot(x = faults, y = bandCurve, 
     type = "l", xlab = "faults", ylab = "bandwidth", col = "blue",
     main = "Best bandwidth vs faults"
)

# Save data
bestBand = data.frame(faults = faults, bestBand = bandCurve)
saveRDS(object = bestBand, file = "data.rds", ascii = TRUE)
